# Generated by Django 5.0.1 on 2024-01-02 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Questions",
            new_name="Question",
        ),
    ]
